<?php
	// module/Category/view/category/category/index.phtml:
	$title = 'My categorys';
	$this->headTitle($title);
?>

<h1><?= $this->escapeHtml($title) ?></h1>

<p>
	<a href="<?= $this->url('category', ['action' => 'add']) ?>">Add new category</a>
</p>

<table class="table">
	<tr>
		<th>CategoryName</th>
		<th>Description</th>
		<th>&nbsp;</th>
	</tr>
<?php foreach ($categorys as $category) : ?>
	<tr>
		<td><?= $this->escapeHtml($category->CategoryName) ?></td>
		<td><?= $this->escapeHtml($category->Description) ?></td>
		<td>
			<a href="<?= $this->url('category', ['action' => 'edit', 'CategoryID' => $category->CategoryID]) ?>">Edit</a>
			<a href="<?= $this->url('category', ['action' => 'delete', 'CategoryID' => $category->CategoryID]) ?>">Delete</a>
		</td>
	</tr>
<?php endforeach; ?>
</table>
